server:
  port: 8080

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/resource-server-db"
    username: postgres
    password: postgres

  zipkin:
    enabled: false

  flyway:
    locations: classpath:migration