logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-bean-definition-overriding: true

client:
  application:
    port: 7070

